#ifndef _SMARTRF_SETTINGS_H_
#define _SMARTRF_SETTINGS_H_

//*********************************************************************************
// Generated by SmartRF Studio version 2.10.0 (build#110)
// The applied template is compatible with CC13x0 SDK 2.20.xx.xx
// Device: CC1310 Rev. 2.1 (Rev. B)
//
//*********************************************************************************
#include <ti/devices/DeviceFamily.h>
#include DeviceFamily_constructPath(driverlib/rf_mailbox.h)
#include DeviceFamily_constructPath(driverlib/rf_common_cmd.h)
#include DeviceFamily_constructPath(driverlib/rf_prop_cmd.h)
#include <ti/drivers/rf/RF.h>


// TX Power table size definition
#define TX_POWER_TABLE_SIZE 17


// TX Power Table Object
extern RF_TxPowerTable_Entry txPowerTable[TX_POWER_TABLE_SIZE];


// TI-RTOS RF Mode Object
extern RF_Mode RF_prop;


// RF Core API commands
extern rfc_CMD_PROP_RADIO_DIV_SETUP_t RF_cmdPropRadioDivSetup;
extern rfc_CMD_FS_t RF_cmdFs;
extern rfc_CMD_TX_TEST_t RF_cmdTxTest;


// RF Core API Overrides
extern uint32_t pOverrides[];


#endif // _SMARTRF_SETTINGS_H_

